package cn.lovemm.model;

import java.util.Date;

public class BlogUserConfig extends BlogUserConfigKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user_config.CONFIG_VALUE
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user_config.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user_config.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    private Date lastModTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user_config.CONFIG_VALUE
     *
     * @return the value of blog_user_config.CONFIG_VALUE
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user_config.CONFIG_VALUE
     *
     * @param configValue the value for blog_user_config.CONFIG_VALUE
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user_config.CREATE_TIME
     *
     * @return the value of blog_user_config.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user_config.CREATE_TIME
     *
     * @param createTime the value for blog_user_config.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user_config.LAST_MOD_TIME
     *
     * @return the value of blog_user_config.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public Date getLastModTime() {
        return lastModTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user_config.LAST_MOD_TIME
     *
     * @param lastModTime the value for blog_user_config.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public void setLastModTime(Date lastModTime) {
        this.lastModTime = lastModTime;
    }
}