package cn.lovemm.model;

import java.util.Date;
import java.util.Map;

public class BlogUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.USER_TEL
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.USER_MAIL
     *
     * @mbggenerated
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.USER_ACCOUNT
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.USER_PWD
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.REGISTER_IP
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.LOGIN_TIMES
     *
     * @mbggenerated
     */
    private Integer loginTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.LAST_LOGIN_IP
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.HEADPHOTO_URL
     *
     * @mbggenerated
     */
    private String headphotoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.USER_ID
     *
     * @return the value of blog_user.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.USER_ID
     *
     * @param userId the value for blog_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.USER_TEL
     *
     * @return the value of blog_user.USER_TEL
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.USER_TEL
     *
     * @param userTel the value for blog_user.USER_TEL
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.USER_MAIL
     *
     * @return the value of blog_user.USER_MAIL
     *
     * @mbggenerated
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.USER_MAIL
     *
     * @param userMail the value for blog_user.USER_MAIL
     *
     * @mbggenerated
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.USER_ACCOUNT
     *
     * @return the value of blog_user.USER_ACCOUNT
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.USER_ACCOUNT
     *
     * @param userAccount the value for blog_user.USER_ACCOUNT
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.USER_PWD
     *
     * @return the value of blog_user.USER_PWD
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.USER_PWD
     *
     * @param userPwd the value for blog_user.USER_PWD
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.STATUS
     *
     * @return the value of blog_user.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.STATUS
     *
     * @param status the value for blog_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.CREATE_TIME
     *
     * @return the value of blog_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.CREATE_TIME
     *
     * @param createTime the value for blog_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.REGISTER_IP
     *
     * @return the value of blog_user.REGISTER_IP
     *
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.REGISTER_IP
     *
     * @param registerIp the value for blog_user.REGISTER_IP
     *
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.LOGIN_TIMES
     *
     * @return the value of blog_user.LOGIN_TIMES
     *
     * @mbggenerated
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.LOGIN_TIMES
     *
     * @param loginTimes the value for blog_user.LOGIN_TIMES
     *
     * @mbggenerated
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.LAST_LOGIN_IP
     *
     * @return the value of blog_user.LAST_LOGIN_IP
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for blog_user.LAST_LOGIN_IP
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.LAST_LOGIN_TIME
     *
     * @return the value of blog_user.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for blog_user.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.NICK_NAME
     *
     * @return the value of blog_user.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.NICK_NAME
     *
     * @param nickName the value for blog_user.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.HEADPHOTO_URL
     *
     * @return the value of blog_user.HEADPHOTO_URL
     *
     * @mbggenerated
     */
    public String getHeadphotoUrl() {
        return headphotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.HEADPHOTO_URL
     *
     * @param headphotoUrl the value for blog_user.HEADPHOTO_URL
     *
     * @mbggenerated
     */
    public void setHeadphotoUrl(String headphotoUrl) {
        this.headphotoUrl = headphotoUrl == null ? null : headphotoUrl.trim();
    }

    /**
     * 用户配置
     */
    private Map<String, Object> config;

    public Map<String, Object> getConfig() {
        return config;
    }

    public void setConfig(Map<String, Object> config) {
        this.config = config;
    }
}