package cn.lovemm.model;

public class BlogArticleWithBLOBs extends BlogArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_CONTENT
     *
     * @mbggenerated
     */
    private String artContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    private String artOriContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_CONTENT
     *
     * @return the value of blog_article.ART_CONTENT
     *
     * @mbggenerated
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_CONTENT
     *
     * @param artContent the value for blog_article.ART_CONTENT
     *
     * @mbggenerated
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent == null ? null : artContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_ORI_CONTENT
     *
     * @return the value of blog_article.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    public String getArtOriContent() {
        return artOriContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_ORI_CONTENT
     *
     * @param artOriContent the value for blog_article.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    public void setArtOriContent(String artOriContent) {
        this.artOriContent = artOriContent == null ? null : artOriContent.trim();
    }
}