package cn.lovemm.model;

import java.util.Date;

public class BlogTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.INDEX
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.TAG_ID
     *
     * @return the value of blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.TAG_ID
     *
     * @param tagId the value for blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.TAG_NAME
     *
     * @return the value of blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.TAG_NAME
     *
     * @param tagName the value for blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.CREATE_TIME
     *
     * @return the value of blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.CREATE_TIME
     *
     * @param createTime the value for blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.INDEX
     *
     * @return the value of blog_tag.INDEX
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.INDEX
     *
     * @param index the value for blog_tag.INDEX
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}