package cn.lovemm.model;

import java.util.Date;

public class BlogCorpus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.COR_ID
     *
     * @mbggenerated
     */
    private String corId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.COR_NAME
     *
     * @mbggenerated
     */
    private String corName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    private Date lastModTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.COR_ID
     *
     * @return the value of blog_corpus.COR_ID
     *
     * @mbggenerated
     */
    public String getCorId() {
        return corId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.COR_ID
     *
     * @param corId the value for blog_corpus.COR_ID
     *
     * @mbggenerated
     */
    public void setCorId(String corId) {
        this.corId = corId == null ? null : corId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.COR_NAME
     *
     * @return the value of blog_corpus.COR_NAME
     *
     * @mbggenerated
     */
    public String getCorName() {
        return corName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.COR_NAME
     *
     * @param corName the value for blog_corpus.COR_NAME
     *
     * @mbggenerated
     */
    public void setCorName(String corName) {
        this.corName = corName == null ? null : corName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.USER_ID
     *
     * @return the value of blog_corpus.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.USER_ID
     *
     * @param userId the value for blog_corpus.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.CREATE_TIME
     *
     * @return the value of blog_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.CREATE_TIME
     *
     * @param createTime the value for blog_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.STATUS
     *
     * @return the value of blog_corpus.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.STATUS
     *
     * @param status the value for blog_corpus.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_corpus.LAST_MOD_TIME
     *
     * @return the value of blog_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public Date getLastModTime() {
        return lastModTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_corpus.LAST_MOD_TIME
     *
     * @param lastModTime the value for blog_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public void setLastModTime(Date lastModTime) {
        this.lastModTime = lastModTime;
    }
}