package cn.lovemm.model;

public class BlogResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_ID
     *
     * @mbggenerated
     */
    private String resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_NAME
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.P_RES_ID
     *
     * @mbggenerated
     */
    private String pResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_TYPE
     *
     * @mbggenerated
     */
    private Integer resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_INDEX
     *
     * @mbggenerated
     */
    private Integer resIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_URL
     *
     * @mbggenerated
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.PERMISSION
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_resource.RES_ICON
     *
     * @mbggenerated
     */
    private String resIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_ID
     *
     * @return the value of blog_resource.RES_ID
     *
     * @mbggenerated
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_ID
     *
     * @param resId the value for blog_resource.RES_ID
     *
     * @mbggenerated
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_NAME
     *
     * @return the value of blog_resource.RES_NAME
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_NAME
     *
     * @param resName the value for blog_resource.RES_NAME
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.P_RES_ID
     *
     * @return the value of blog_resource.P_RES_ID
     *
     * @mbggenerated
     */
    public String getpResId() {
        return pResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.P_RES_ID
     *
     * @param pResId the value for blog_resource.P_RES_ID
     *
     * @mbggenerated
     */
    public void setpResId(String pResId) {
        this.pResId = pResId == null ? null : pResId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_TYPE
     *
     * @return the value of blog_resource.RES_TYPE
     *
     * @mbggenerated
     */
    public Integer getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_TYPE
     *
     * @param resType the value for blog_resource.RES_TYPE
     *
     * @mbggenerated
     */
    public void setResType(Integer resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.STATUS
     *
     * @return the value of blog_resource.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.STATUS
     *
     * @param status the value for blog_resource.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_INDEX
     *
     * @return the value of blog_resource.RES_INDEX
     *
     * @mbggenerated
     */
    public Integer getResIndex() {
        return resIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_INDEX
     *
     * @param resIndex the value for blog_resource.RES_INDEX
     *
     * @mbggenerated
     */
    public void setResIndex(Integer resIndex) {
        this.resIndex = resIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_URL
     *
     * @return the value of blog_resource.RES_URL
     *
     * @mbggenerated
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_URL
     *
     * @param resUrl the value for blog_resource.RES_URL
     *
     * @mbggenerated
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.PERMISSION
     *
     * @return the value of blog_resource.PERMISSION
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.PERMISSION
     *
     * @param permission the value for blog_resource.PERMISSION
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_resource.RES_ICON
     *
     * @return the value of blog_resource.RES_ICON
     *
     * @mbggenerated
     */
    public String getResIcon() {
        return resIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_resource.RES_ICON
     *
     * @param resIcon the value for blog_resource.RES_ICON
     *
     * @mbggenerated
     */
    public void setResIcon(String resIcon) {
        this.resIcon = resIcon == null ? null : resIcon.trim();
    }
}