package cn.lovemm.model;

public class BlogUserConfigKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user_config.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user_config.CONFIG_KEY
     *
     * @mbggenerated
     */
    private String configKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user_config.USER_ID
     *
     * @return the value of blog_user_config.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user_config.USER_ID
     *
     * @param userId the value for blog_user_config.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user_config.CONFIG_KEY
     *
     * @return the value of blog_user_config.CONFIG_KEY
     *
     * @mbggenerated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user_config.CONFIG_KEY
     *
     * @param configKey the value for blog_user_config.CONFIG_KEY
     *
     * @mbggenerated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }
}