package cn.lovemm.model;

public class BlogRoleResourceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_role_resource.RES_ID
     *
     * @mbggenerated
     */
    private String resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_role_resource.ROLE_ID
     *
     * @return the value of blog_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_role_resource.ROLE_ID
     *
     * @param roleId the value for blog_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_role_resource.RES_ID
     *
     * @return the value of blog_role_resource.RES_ID
     *
     * @mbggenerated
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_role_resource.RES_ID
     *
     * @param resId the value for blog_role_resource.RES_ID
     *
     * @mbggenerated
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }
}