package cn.lovemm.model;

import java.util.Date;

public class SDataDic extends SDataDicKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    private String dicValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    private String dicDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_data_dic.DIC_VALUE
     *
     * @return the value of s_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_data_dic.DIC_VALUE
     *
     * @param dicValue the value for s_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_data_dic.DIC_DESC
     *
     * @return the value of s_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    public String getDicDesc() {
        return dicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_data_dic.DIC_DESC
     *
     * @param dicDesc the value for s_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    public void setDicDesc(String dicDesc) {
        this.dicDesc = dicDesc == null ? null : dicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_data_dic.CREATE_TIME
     *
     * @return the value of s_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_data_dic.CREATE_TIME
     *
     * @param createTime the value for s_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_data_dic.MOD_TIME
     *
     * @return the value of s_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_data_dic.MOD_TIME
     *
     * @param modTime the value for s_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }
}