package cn.lovemm.mapper;

import cn.lovemm.model.BlogUserConfig;
import cn.lovemm.model.BlogUserConfigExample;
import cn.lovemm.model.BlogUserConfigKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogUserConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int countByExample(BlogUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int deleteByExample(BlogUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BlogUserConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int insert(BlogUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int insertSelective(BlogUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    List<BlogUserConfig> selectByExample(BlogUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    BlogUserConfig selectByPrimaryKey(BlogUserConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogUserConfig record, @Param("example") BlogUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogUserConfig record, @Param("example") BlogUserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogUserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogUserConfig record);
}