package cn.lovemm.mapper;

import cn.lovemm.model.BlogResource;
import cn.lovemm.model.BlogResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int countByExample(BlogResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int deleteByExample(BlogResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int insert(BlogResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int insertSelective(BlogResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    List<BlogResource> selectByExample(BlogResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    BlogResource selectByPrimaryKey(String resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogResource record, @Param("example") BlogResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogResource record, @Param("example") BlogResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogResource record);
}