package cn.lovemm.mapper;

import cn.lovemm.model.BlogUser;
import cn.lovemm.model.BlogUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int countByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int deleteByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int insert(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int insertSelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    List<BlogUser> selectByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    BlogUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogUser record);
}