package cn.lovemm.mapper;

import cn.lovemm.model.BlogCorpus;
import cn.lovemm.model.BlogCorpusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogCorpusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int countByExample(BlogCorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int deleteByExample(BlogCorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String corId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int insert(BlogCorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int insertSelective(BlogCorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    List<BlogCorpus> selectByExample(BlogCorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    BlogCorpus selectByPrimaryKey(String corId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogCorpus record, @Param("example") BlogCorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogCorpus record, @Param("example") BlogCorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogCorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_corpus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogCorpus record);
}