package cn.lovemm.mapper;

import cn.lovemm.model.BlogUserRoleExample;
import cn.lovemm.model.BlogUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int countByExample(BlogUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(BlogUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BlogUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int insert(BlogUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int insertSelective(BlogUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    List<BlogUserRoleKey> selectByExample(BlogUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogUserRoleKey record, @Param("example") BlogUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogUserRoleKey record, @Param("example") BlogUserRoleExample example);
}