package cn.lovemm.mapper;

import cn.lovemm.model.SDataDic;
import cn.lovemm.model.SDataDicExample;
import cn.lovemm.model.SDataDicKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SDataDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int countByExample(SDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int deleteByExample(SDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SDataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int insert(SDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int insertSelective(SDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    List<SDataDic> selectByExample(SDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    SDataDic selectByPrimaryKey(SDataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SDataDic record, @Param("example") SDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SDataDic record, @Param("example") SDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_data_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SDataDic record);
}