package cn.lovemm.mapper;

import cn.lovemm.model.SResource;
import cn.lovemm.model.SResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int countByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int deleteByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int insert(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int insertSelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    List<SResource> selectByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    SResource selectByPrimaryKey(String resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SResource record);
}