package cn.lovemm.mapper;

import cn.lovemm.model.SUserRoleExample;
import cn.lovemm.model.SUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int countByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int insert(SUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int insertSelective(SUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    List<SUserRoleKey> selectByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SUserRoleKey record, @Param("example") SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SUserRoleKey record, @Param("example") SUserRoleExample example);
}